baseURL = "https://santimj.com/"
languageCode = "en"
title = "Santiago Moreno Jauregu√≠zar"
# theme = ""  # Empty - using custom layouts

[menu]

  [[menu.main]]
    name   = "SMJ"
    url    = "/smj/"
    weight = 1

  [[menu.main]]
    name   = "Engineering"
    url    = "/engineering/"
    weight = 10

  [[menu.main]]
    name   = "Teaching"
    url    = "/teaching/"
    weight = 20

  [[menu.main]]
    name   = "Personal Development"
    url    = "/personal-development/"
    weight = 30

  [[menu.main]]
    name   = "The Artist"
    url    = "/the-artist/"
    weight = 40

  [[menu.main]]
    name   = "My Sky"
    url    = "/astrology/"
    weight = 50

  [[menu.main]]
    name   = "Complementary"
    url    = "/other-interests/"
    weight = 60
